version: '3.4'

services:
  ocelotapigateway:
    image: localhost/ag:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 7186:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;https://+:7186
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Kinoroom
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/gateway.pfx
    volumes:
      - ~/.aspnet/https:/https:ro